### PR TITLE
Using tibia stats instead of tibia-api

### PR DESCRIPTION
**Pull request by Ethaan**

### CODE REVIEW

**Comment by alexsandrejr** [comment]
@Ethaan 
the installation process is very complicated.
The bot creates the rooms and the permissions but does not provide the permissions for the teamspeak user as shown in the following images:

[img]https://prnt.sc/rzg8hh[/img]

[img]https://prnt.sc/rzgayh[/img]

**Comment by alexsandrejr** [comment]
does it only work on teamspeak server 3.2.0+?
my server is 3.0.13.8!

**Comment by alexsandrejr** [comment]
I can provide you with a vps so you can test the bot and maybe make a video teaching you how to install mongodb and the bot.

**Comment by Ethaan** [comment]
@alexsandrejr the installation is complex but thats intended, about the Server 3.2.0 vs 3.0.13.8, i'm not 100% sure about that, i can take a look and see whats going on.

for 

> The bot creates the rooms and the permissions but does not provide the permissions for the

Thats weird, can you try deleting the `mysql` file and wipeout the database, there is a `ts3-restart` script you can run.

> the installation process is very complicated.

The bot is free and that mean you need to do some extra stuff, i can go and create some webpage where you guys can login and create new bots, but still that will take me some time, i think something we can do is create some scripts people can run and setup everything so there is no download needed.

Other thing i can do is setup a quick webpage with examplanation to download the BOT itself with the script, and make that easy to (so you don't need to install GIT manually and all that)

> I can provide you with a vps

Yea email me that so i can start testing scripts and making the instalation process easier.

**Comment by alexsandrejr** [comment]
@Ethaan 
I sent you an email with the necessary data for the connection of the vps.

**Comment by Ethaan** [comment]
Thanks @alexsandrejr been pretty busy this days, will try to take a look soon

**Comment by alexsandrejr** [comment]
quando for utilizar a vps me avise para eu poder reativala. Pois ela
consome meus creditos na empresa.

Em qui., 16 de abr. de 2020 às 13:51, Ethan <notifications@github.com>
escreveu:

**Comment by alexsandrejr** [comment]
when you use the vps let me know so I can reactivate it. Because it
consumes my credits in the company.


Em sex., 17 de abr. de 2020 às 23:11, Alexsandre Roberto Carneiro Lopes
Júnior <alexsandrecasa@gmail.com> escreveu:

**Comment by alexsandrejr** [comment]
@Ethaan do you know how to solve these possible errors? because I think they are making the bot not work as it should.
powershell

**Pull request merged**
